name: budget_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.8
  logger: ^2.5.0
  cloud_firestore: ^5.6.5
  firebase_auth: ^5.5.1
  flutter_hooks: ^0.21.2
  hooks_riverpod: ^2.6.1
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.2
  sign_button: ^2.0.6
  url_launcher: ^6.3.1
  flutter_svg: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
